---
kind: List
apiVersion: v1
metadata:
  name: "{{ NAME }}"
  annotations:
    openshift.io/display-name: Generic Build Pod
    description: "{{ NAME }} build pod template pre-configured to use a nexus in the
      same project/namespace"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "{{ NAME }}"
    name: jenkins-slave-base-rhel7
  spec:
    tags:
    - from:
        kind: DockerImage
        name: openshift/jenkins-slave-base-rhel7:{{ SLAVE_IMAGE_TAG }}
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "{{ NAME }}"
      role: jenkins-slave
    name: "{{ NAME }}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "{{ NAME }}"
      type: image
    name: "{{ NAME }}"
  spec:
    nodeSelector: 
    output:
      to:
        kind: ImageStreamTag
        name: "{{ NAME }}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "{{ SOURCE_CONTEXT_DIR }}"
      git:
        ref: "{{ SOURCE_REPOSITORY_REF }}"
        uri: "{{ SOURCE_REPOSITORY_URL }}"
      sourceSecret:
        name: "{{ SOURCE_REPOSITORY_SECRET }}"
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: "{{ DOCKERFILE_PATH }}"
        from:
          kind: DockerImage
          name: "{{ BUILDER_IMAGE_NAME }}"
      type: Docker
    triggers:
    - github:
        secret: "{{ GITHUB_WEBHOOK_SECRET }}"
      type: GitHub
    - type: ConfigChange
    - type: ImageChange
