---
kind: List
apiVersion: v1
metadata:
  name: s2i-app-build
  annotations:
    openshift.io/display-name: S2I App Build Template
    description: S2I binary build config to create an image with your app baked in.
    iconClass: fa-cube
    tags: s2i
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "{{ NAME }}"
      app: "{{ NAME }}"
    name: "{{ NAME }}"
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "{{ NAME }}"
      name: "{{ NAME }}-pipeline"
      type: pipeline
      app: "{{ NAME }}"
    name: "{{ NAME }}-pipeline"
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "{{ PIPELINE_CONTEXT_DIR }}"
      git:
        ref: "{{ PIPELINE_SOURCE_REPOSITORY_REF }}"
        uri: "{{ PIPELINE_SOURCE_REPOSITORY_URL }}"
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: {{ JENKINSFILE_PATH }}
      type: JenkinsPipeline
    triggers:
    - type: ConfigChange
    - type: Bitbucket
      bitbucket:
        secret: "{{ BITBUCKET_WEBHOOK }}"
    - type: Generic
      generic:
        secret: "{{ GENERIC_WEBHOOK }}"
    - type: GitHub
      github:
        secret: "{{ GITHUB_WEBHOOK }}"
    - type: GitLab
      gitlab:
        secret: "{{ GITLAB_WEBHOOK }}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "{{ NAME }}"
      name: "{{ NAME }}"
      type: image
      app: "{{ NAME }}"
    name: "{{ NAME }}"
  spec:
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "{{ NAME }}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "{{ GIT_SOURCE_CONTEXT_DIR }}"
      git:
        ref: "{{ GIT_SOURCE_REF }}"
        uri: "{{ GIT_SOURCE_URI }}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "{{ S2I_BASE_IMAGE }}"
          namespace: openshift
      type: Source
  status:
    lastVersion: 1
