---
kind: List
apiVersion: v1
metadata:
  name: "add-role-to-group"
  annotations:
    openshift.io/display-name: Group and role binding Access template
    description: RoleBinding to give access to project
    iconClass: icon-jenkins
labels:
  template: role-to-group-binding
objects:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: {{ GROUP }}_{{ ROLE }}_role
  roleRef:
    name: "{{ ROLE }}"   
  subjects:
  - kind: Group
    name: {{ GROUP }}                            
  groupNames:
  - "{{ GROUP }}"
