---
kind: List
objects:
- readOnlyRootFilesystem: false
  users:
  - system:serviceaccount:{{ NAMESPACE }}:{{ NAME }}
  allowPrivilegedContainer: false
  allowHostPorts: false
  groups:
  - system:cluster-admins
  allowHostPID: false
  allowHostDirVolumePlugin: false
  allowedCapabilities: []
  kind: SecurityContextConstraints
  allowHostIPC: false
  runAsUser:
    type: RunAsAny
  supplementalGroups:
    type: RunAsAny
  fsGroup:
    type: RunAsAny
  apiVersion: v1
  priority: "{{ PRIORITY_LEVEL }}"
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  seLinuxContext:
    type: MustRunAs
  defaultAddCapabilities: []
  allowHostNetwork: false
  requiredDropCapabilities:
  - MKNOD
  metadata:
    annotations:
      kubernetes.io/description: anyuid provides all features of the restricted SCC
        but allows users to run with any UID and any GID.
    name: "{{ NAME }}-anyuid"
apiVersion: v1
