---
kind: List
apiVersion: v1
metadata:
  name: java-app-deploy
  annotations:
    openshift.io/display-name: Fabric8 Deploy Rolebinding
    description: A template to support the role bindings needed fabric8 k8s libraries
    iconClass: icon-cube
    tags: cube
objects:
- apiVersion: v1
  kind: RoleBinding
  groupNames:
  - system:serviceaccounts:{{ APP_NAMESPACE }}
  metadata:
    name: view
  roleRef:
    name: view
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:{{ APP_NAMESPACE }}
  userNames: 
