---
kind: List
apiVersion: v1
metadata:
  name: "{{ NAME }}"
  annotations:
    openshift.io/display-name: Generic Dockerfile Build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "{{ NAME }}"
      app: "{{ NAME }}"
    name: "{{ NAME }}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "{{ NAME }}"
      app: "{{ NAME }}"
      type: "image"
    name: "{{ NAME }}"
  spec:
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "{{ NAME }}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "{{ SOURCE_CONTEXT_DIR }}"
      git:
        ref: "{{ SOURCE_REPOSITORY_REF }}"
        uri: "{{ SOURCE_REPOSITORY_URL }}"
      type: Git
      sourceSecret:
        name: "{{ SOURCE_REPOSITORY_SECRET }}"
    strategy:
      type: Docker
    triggers:
    - type: GitHub
      github:
        secret: "{{ WEBHOOK_SECRET }}"
    - type: GitLab
      gitlab:
        secret: "{{ WEBHOOK_SECRET }}"
    - type: BitBucket
      gitlab:
        secret: "{{ WEBHOOK_SECRET }}"
    - type: Generic
      generic:
        secret: "{{ WEBHOOK_SECRET }}"
        allowEnv: true
    - type: ConfigChange
    - type: ImageChange
