---
kind: List
apiVersion: v1
metadata:
  name: jenkins-pipeline-no-ocp-triggers
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "{{ NAME }}"
      name: "{{ NAME }}-pipeline"
      type: "pipeline"
    name: "{{ NAME }}-pipeline"
  spec:
    runPolicy: "{{ RUN_POLICY }}"
    source:
      contextDir: "{{ PIPELINE_CONTEXT_DIR }}"
      git:
        ref: "{{ PIPELINE_SOURCE_REPOSITORY_REF }}"
        uri: "{{ PIPELINE_SOURCE_REPOSITORY_URL }}"
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: "{{ PIPELINE_FILENAME }}"
      type: JenkinsPipeline
